project_id = "yoahbelmymuuyqwvfogr"

[functions.send-emergency-alerts]
verify_jwt = false

[functions.promote-to-admin]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
